services:
  - type: web
    name: haus-of-basquiat-portal
    runtime: node
    plan: starter  # Free tier
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: haus-of-basquiat-db
          property: connectionString
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false  # Set manually in Render dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false  # Set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        value: https://haus-of-basquiat-portal.onrender.com

databases:
  - name: haus-of-basquiat-db
    databaseName: hausofbasquiat
    user: hausofbasquiat
    region: oregon
    plan: free  # Free tier PostgreSQL
    postgresMajorVersion: 15