name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

permissions:
  contents: read
  deployments: write
  actions: read
  checks: write

jobs:
  test-and-deploy:
    name: Test and Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
        env:
          NODE_ENV: test

      - name: Run type check
        run: npm run type-check

      - name: Run lint
        run: npm run lint

      - name: Run security audit
        run: npm run security:audit

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Deploy to Railway
        uses: railway-deploy/railway-deploy@v3
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service_id: ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          NODE_ENV: production